# Generated by Django 4.2.15 on 2024-09-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
