# Generated by Django 4.2.15 on 2024-09-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 17, 43, 50, 841256, tzinfo=datetime.timezone.utc)),
        ),
    ]
