# Generated by Django 4.2.15 on 2024-09-02 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 10, 59, 44, 24812, tzinfo=datetime.timezone.utc)),
        ),
    ]
