# Generated by Django 4.2.15 on 2024-09-02 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 11, 24, 31, 302813, tzinfo=datetime.timezone.utc)),
        ),
    ]
