# Generated by Django 4.2.15 on 2024-09-02 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 13, 53, 33, 608267, tzinfo=datetime.timezone.utc)),
        ),
    ]
